name: Nations
main: me.ionaru.nations.Nations
version: ${project.version}
description: Nations plugin
commands:
    nations:
        description: The all-in-1 command for nations.
        aliases: [n,nation,nations]