# Default configuration file for Nations plugin.


#THIS IS A DUPLICATe.  THE REAL ONE IS FOUND IN src/main/java/resources



plugin_enabled: true
#Switch this option to 'false' to disable the entire plugin.
